version: '3'
services:
  database:
    container_name: hotel_crm_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - ../../docker/database-root.env  # load the root user password (user root with this password will have full privileges)
      - ../../docker/database.env       # load application specific user and database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "crm_mysql:/data"
      - ../../docker/mysql/sql/:/docker-entrypoint-initdb.d/ # load the sql files from here on database creation
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80 # open http://localhost:8080 in your browser to access phpmyadmin console
    links:
      - database
    env_file:
      - ../../docker/phpmyadmin.env # load environment variables necessary to create the connection to the database container

  php:
    container_name: hotel_crm_php
    # for your php application you need to create a docker image
    build:
      dockerfile: php/Dockerfile
    env_file:
      - ../../docker/database.env # load database configurations to be able to connect to the database
    ports:
      - "9000:9000"
    environment:
      - PHP_MEMORY_LIMIT=512M
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./code:/var/www/html:cached
    working_dir: /var/www/html

  redis:
    container_name: hotel_crm_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "crm_redis:/data"

  nginx:
    container_name: hotel_crm_nginx
    build:
      dockerfile: ../../docker/nginx/Dockerfile
    image: nginx:1.21
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/html:cached

volumes:
  crm_mysql:
    driver: local

  crm_redis:
    driver: local